server:
  port: ${port:8502}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8503/eureka/}

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: ${git.uri:http://git.oschina.net/chinacvic/xbin-store-cloud.git}
          username: ${git.username:chinacvic}
          password: ${git.password:Spearhead1234}
          search-paths: config/*